Extend webshop
augustin-wien/augustin-backend pull request #105
Opened 2023-10-24 16:36 UTC by lebe1

# Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Description

**IMPORTANT TO KNOW**

**CHANGES**

- Extends handlers and queries for choosing several items in webshop
**TODO**

- Adjust create demo transaction by using item.IDs instead of item[2], which is a dynamic list

# Checklist:

- [ ] I have commented my code (or ChatGPT did), particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings, neither in my IDE nor in my browser
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-11-02 10:49 UTC, nanu-c requested changes

2023-11-02 10:49 UTC, nanu-c commented on app/handlers/handlers.go
> +	for _, entry := range order.Entries {
Seems like solved

2023-11-02 10:49 UTC, nanu-c commented on app/database/devtools.go
> +// item[3] = Digital newspaper license
Do we need to manually change the items in the db?

2023-11-02 10:51 UTC, nanu-c commented on app/database/devtools.go
> +// item[3] = Digital newspaper license
nope 
![image](https://github.com/augustin-wien/augustin-backend/assets/404058/e6a228b0-5b0f-486a-a825-1e41fb0bd591)

2023-11-02 11:09 UTC, lebe1 commented on app/database/devtools.go
> +// item[3] = Digital newspaper license
Nope we don't the order was just not correctly listed. The license has to be created before the digital newspaper item and is therefore listed before the item...
But if you would be so kind: Could you remove these quotation marks in "Transaktionskosten"?
I removed them from the `.env.example` so we don't have that problem again.

2023-11-02 11:11 UTC, lebe1 commented on app/database/setup.go
> +		Name:        config.Config.DonationName,
Okay but then I would do the same with the TransactionCostsName to stay consistent wouldn't you?

2023-11-02 11:18 UTC, lebe1 commented on app/handlers/handlers.go
> +	for _, entry := range order.Entries {
I remain having this error and will replace it. Something is broken with our Github Linter that it does not claim this failure in our actions anymore...
![image](https://github.com/augustin-wien/augustin-backend/assets/38591956/d2db0399-7332-4184-a8ab-76ed7ba318ed)

2023-11-02 11:18 UTC, lebe1 commented on app/handlers/handlers.go
> +	for _, entry := range order.Entries {
Even though since there is an if-case for each entry, I should not append all the entries at once since we would also receive the transaction costs payments

2023-11-02 11:23 UTC, lebe1 commented on app/database/setup.go
> +		Name:        config.Config.DonationName,
On a second thought I think I prefer having the option to rename these two items in the setup in case of a generalisation approach and they become visible

2023-11-03 19:16 UTC, nanu-c submitted a review, later dismissed

2023-11-09 15:53 UTC, nanu-c approved these changes

2023-11-09 15:59 UTC, merged