Handlers4
augustin-wien/augustin-backend pull request #31
Opened 2023-08-14 12:28 UTC by JoelForamitti

# Type of change

- [x] New feature (non-breaking change which adds functionality)

# Description

- Upload function for Item API with multipart form

# Checklist:

- [ ] I have commented my code (or ChatGPT did), particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings, neither in my IDE nor in my browser
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-08-14 13:15 UTC, nanu-c requested changes

2023-08-14 13:15 UTC, nanu-c commented on app/handlers/router.go
> +	r.Handle("/docs/*", http.StripPrefix("/docs/", fs2))
maybe rename `fs2` to `fs_docs`

2023-08-14 13:15 UTC, nanu-c commented on app/handlers/handlers_test.go
> +	// Read
Please run the linter to align the the lines nicely ;)

2023-08-14 13:21 UTC, JoelForamitti commented on app/handlers/handlers_test.go
> +	// Read
done

2023-08-14 13:22 UTC, JoelForamitti commented on app/handlers/handlers.go
> +	log.Info("mForm: ", mForm)
removed

2023-08-21 08:43 UTC, nanu-c requested changes

2023-08-21 08:43 UTC, nanu-c commented on app/handlers/router.go
> +	r.Handle("/img/*", http.StripPrefix("/img/", fs_img))
How do you avoid to handle urls like `../../../etc/passwd`?

2023-08-21 12:43 UTC, JoelForamitti commented on app/handlers/router.go
> +	r.Handle("/img/*", http.StripPrefix("/img/", fs_img))
I tested it and it is not possible. The only way that going to parent that is allowed is /../doc since it points to another fileserver.

2023-08-21 12:43 UTC, JoelForamitti commented
I changed docs to doc to avoid overlap with the /docs directory where the documentation lies. I also added volumes for file persistence for production

2023-08-21 13:39 UTC, nanu-c approved these changes

2023-08-21 13:40 UTC, merged