Demo data for developing
augustin-wien/augustin-backend pull request #36
Opened 2023-09-12 15:06 UTC by lebe1

# Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Description

This PR adds new demo data for developing and fixes both `InitiateSettings()` and `InitiateAccounts()` to not create several Accounts or let an error occur due to unique id correlation.

# Checklist:

- [ ] I have commented my code (or ChatGPT did), particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings, neither in my IDE nor in my browser
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-09-13 06:24 UTC, nanu-c commented
please rebase on main branch

2023-09-14 13:54 UTC, jofmi requested changes

2023-09-14 13:54 UTC, jofmi commented on README.md
> +1. For developing in frontend or backend only, run this command
in frontend or backend? this is just for backend, no?

2023-09-14 13:54 UTC, jofmi commented on README.md
> +When variable `DEVELOPMENT=true`, demo data will be created during container creation. This data can be used for development purposes.
Might CREATE_DEMO_DATA be more explicit?

2023-09-14 13:54 UTC, jofmi commented on app/database/db.go
> +	isInitialized := false
I'd suggest to set this variable with an explicit check like db.CheckInitialized().

2023-09-14 13:54 UTC, jofmi commented on app/database/devtools.go
> +	db.CreateDevItems()
Should we name all internal functions with lowercase c so that only CreateDevData gets exported?

2023-09-14 13:54 UTC, jofmi commented on app/database/queries.go
> +	}
I would suggest to add load the vendors account from the database and write it to vendor.Account so that the balance can be read

2023-09-14 13:54 UTC, jofmi commented on app/database/queries.go
> +	// Check if the item name already exists
I don't think this is necessary since Item Name is set to unique in the database

2023-09-14 13:54 UTC, jofmi commented on app/database/queries.go
> +	if slices.Contains(existOnceTypes, account.Type) {
Looks great!

2023-09-14 13:54 UTC, jofmi commented on app/database/queries.go
> +	ON CONFLICT (ID) DO NOTHING;
Looks great!

2023-09-14 13:54 UTC, jofmi commented on app/database/queries_test.go
>  	// Create mew account
Pokemon typo :)

2023-09-14 13:54 UTC, jofmi commented on app/database/queries_test.go
> +	require.Equal(t, "red", settings.Color)
Is the demo data enabled in all tests? Because I think some of the handler_tests are based on the assumption that there is no demo data.

2023-09-14 13:54 UTC, jofmi commented on app/handlers/handlers.go
> +	}
I think you need to end with a utils.WriteJSON(w, http.StatusOK, nil)

2023-09-14 15:31 UTC, lebe1 commented on README.md
> +1. For developing in frontend or backend only, run this command
Nope for our frontend devs too. They only care about our API not the Wordpress or PDF-Parser container

2023-09-14 15:33 UTC, lebe1 commented on app/database/db.go
> +	isInitialized := false
Yes, I see your point! My question is though how we implement it in our database. Adding a new field to our settings table or rather create a new table like `dbsettings` since there is a difference in these settings or do you have a different approach in mind?

2023-09-14 15:41 UTC, lebe1 commented on app/database/queries_test.go
> +	require.Equal(t, "red", settings.Color)
This is just the test data copied from the test above 
```go
func Test_UpdateSettings(t *testing.T) {
	// Define settings
	err := Db.UpdateSettings(Settings{
		Color: "red",
		Logo:  "/img/Augustin-Logo-Rechteck.jpg",
	},
	)

	if err != nil {
		t.Errorf("UpdateSettings failed: %v\n", err)
	}
}
```

2023-09-14 16:41 UTC, jofmi commented on README.md
> +1. For developing in frontend or backend only, run this command
ok!

2023-09-14 16:41 UTC, jofmi commented on app/database/db.go
> +	isInitialized := false
i'd go for the new table!

2023-09-14 16:42 UTC, jofmi commented on app/database/db.go
> +	isInitialized := false
or you put it in the existing settings table but leave it out of the queries for that table so that it cannot be edited

2023-09-14 16:42 UTC, jofmi commented on app/database/queries_test.go
> +	require.Equal(t, "red", settings.Color)
ah great then!

2023-09-15 09:44 UTC, lebe1 commented on app/database/db.go
> +	isInitialized := false
In  my new commit you can see my solution. I'm not a hundred percent happy about this solution since it feels a little bit overblown to me. 
1. I decided to create an own table, which stays out of crucial settings data used for API calls
2. I created a migration file because I would like to test how smooth [migrating up and down N versions](https://github.com/jackc/tern#migrating) works with several files before we put everything in production and then have to learn it. Even though, I assume you have already done your tests on it?
3.  DBSettings still has to be initialized each time, which makes everything a little ridicolous of not initializing things twice. But because of the Postgresql Query `INSERT INTO DBSettings (ID, isInitialized) VALUES (1, false) ON CONFLICT (ID) DO NOTHING;` it won't be initilaized twice. 
Same goes for our crucial data like User Types and Settings, which now have first our DBSettings.isInitilized variable to pass and second in both SQL-queries is also a check to not insert their initiating data twice.

2023-09-18 07:05 UTC, jofmi approved these changes

2023-09-18 07:05 UTC, jofmi commented on app/database/db.go
> +	isInitialized := false
We could get a third opinion from @nanu-c, but I think this looks all very good!

2023-09-18 09:01 UTC, merged