Add MoneyLimit to Settings
augustin-wien/augustin-backend pull request #47
Opened 2023-09-19 15:17 UTC by lebe1

# Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Description

Add db field MoneyLimit to Settings table & update queries

# Checklist:

- [ ] I have commented my code (or ChatGPT did), particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings, neither in my IDE nor in my browser
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-09-20 09:43 UTC, jofmi requested changes
The variable is not yet used in CreateOrder

2023-09-20 09:43 UTC, jofmi commented on app/database/types.go
> +	MoneyLimit int
Should we maybe name it "OrderMaxAmount" to be more explicit?

2023-09-20 14:00 UTC, jofmi commented on app/migrations/003_sample_migration.sql
> +ADD COLUMN MaxOrderAmount integer DEFAULT 50;
This would set a limit to 50 Cents.

As it is currently, this can also be Null (which we could interpret as infinite)

2023-09-20 14:00 UTC, jofmi commented on app/database/types.go
> +	MaxOrderAmount int
If it is nullable in the Database, I would use null.int

2023-09-25 13:37 UTC, nanu-c approved these changes

2023-09-25 13:39 UTC, merged