Add account names to payments
augustin-wien/augustin-backend pull request #78
Opened 2023-09-28 16:54 UTC by lebe1

# Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Description

**IMPORTANT TO KNOW**

**CHANGES**

- Adds SenderName to Payments and OrderEntries
- Adds ReceiverName to Payments and OrderEntries
**TODO**

# Checklist:

- [ ] I have commented my code (or ChatGPT did), particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings, neither in my IDE nor in my browser
- [ ] I have added tests that prove my fix is effective or that my feature works

2023-09-28 17:10 UTC, nanu-c commented on app/database/queries.go
> +	rows, err := db.Dbpool.Query(context.Background(), "SELECT ID, Item, Quantity, Price, Sender, Receiver, SenderName, ReceiverName, IsSale FROM OrderEntry WHERE paymentorder = $1", orderID)
shouldn't we use sql joins instead of saving  the names all over the place. What should we do, when the name changes? @jofmi ?

2023-09-28 17:27 UTC, lebe1 commented on app/database/queries.go
> +	rows, err := db.Dbpool.Query(context.Background(), "SELECT ID, Item, Quantity, Price, Sender, Receiver, SenderName, ReceiverName, IsSale FROM OrderEntry WHERE paymentorder = $1", orderID)
Good point on this thought! SQL JOIN should be the preferred way. 
Since the vendors account name relies on the license id, this will never change though. Same goes for all these default account names like "Orga", "Cash" or "UserAnon". Logic for user account names is not implemented yet, which are the only group who would change their name more than once.

2023-09-29 06:27 UTC, jofmi requested changes
What seems to be missing is  how the name is generated in the Account queries.

If you agree with my suggested way of solving this, I could offer to implement the suggested changes myself.

2023-09-29 06:27 UTC, jofmi commented on app/database/queries.go
> +		err = rows.Scan(&entry.ID, &entry.Item, &entry.Quantity, &entry.Price, &entry.Sender, &entry.Receiver, &entry.SenderName, &entry.ReceiverName, &entry.IsSale)
I would suggest to implement a db query GetAccountName() and load this into SenderName and ReceiverName. Like this, the SenderName and ReceiverName is not saved in two different places at the same time.

2023-09-29 06:27 UTC, jofmi commented on app/database/queries.go
> +	err = tx.QueryRow(context.Background(), "INSERT INTO OrderEntry (Item, Price, Quantity, PaymentOrder, Sender, Receiver, SenderName, ReceiverName, IsSale) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
Here and below, I would remove SenderName and ReceiverName in line with the suggestion above to not save this data in the entry object but only load it from account when for GET calls.

2023-09-29 06:27 UTC, jofmi commented on app/migrations/001_payment_model.sql
> +    SenderName varchar(255) NOT NULL,
In line with the suggestions above, I would remove these database fields and load the names directly from account when needed.

2023-09-29 06:28 UTC, jofmi commented on app/database/queries.go
> +	rows, err := db.Dbpool.Query(context.Background(), "SELECT ID, Item, Quantity, Price, Sender, Receiver, SenderName, ReceiverName, IsSale FROM OrderEntry WHERE paymentorder = $1", orderID)
Yes, I think a JOIN would be best but I am not completely sure how it would look like in this case. To speed things up we could also just load the name from the vendor object before as suggested below.

2023-09-29 06:44 UTC, jofmi commented on app/database/queries.go
> +	rows, err := db.Dbpool.Query(context.Background(), "SELECT ID, Item, Quantity, Price, Sender, Receiver, SenderName, ReceiverName, IsSale FROM OrderEntry WHERE paymentorder = $1", orderID)
Ok I think I figured out how to do the JOIN!

2023-09-29 06:56 UTC, jofmi commented
I started trying out a JOIN solution here: https://github.com/augustin-wien/augustin-backend/pull/80

2023-09-29 10:37 UTC, closed without merging